//! AUTO-GENERATED by tools/gen_vendor_manifest.py — do not edit by hand.
//! 列出 `vendor/sel4-src` 下 `.c`/`.S`（默认可为空；对照用官方树在仓外，默认 `../seL4/src`）。

pub const entry_count: usize = 0;

pub fn pathAt(i: usize) []const u8 {
    if (i >= entries.len) return "";
    return entries[i];
}

const entries: [0][]const u8 = .{

};
