#!/usr/bin/env python3
"""Generate mirror_manifest.zig and MODULE_CATALOG.md from vendor/sel4-src."""
from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "vendor" / "sel4-src"
DOC = ROOT / "docs" / "sel4-module-catalog.md"
ZIG = ROOT / "src" / "sel4" / "mirror_manifest.zig"


def include_sel4_src_file(path: pathlib.Path) -> bool:
    """本仓库 AArch64 导向：不收录 AArch32 / ARMv7 / AArch32-only armv8 路径，减轻 vendor C/S 体量。"""
    try:
        rel = path.relative_to(SRC)
    except ValueError:
        return True
    parts = rel.parts
    if len(parts) >= 3 and parts[0] == "arch" and parts[1] == "arm" and parts[2] == "32":
        return False
    if len(parts) >= 4 and parts[:4] == ("arch", "arm", "armv", "armv7-a"):
        return False
    if len(parts) >= 5 and parts[:5] == ("arch", "arm", "armv", "armv8-a", "32"):
        return False
    return True


def main() -> None:
    SRC.mkdir(parents=True, exist_ok=True)
    c_files = sorted(p for p in SRC.rglob("*.c") if include_sel4_src_file(p))
    s_files = sorted(p for p in SRC.rglob("*.S") if include_sel4_src_file(p))
    all_files = c_files + s_files

    ZIG.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "//! AUTO-GENERATED by tools/gen_vendor_manifest.py — do not edit by hand.",
        "//! 与上游 `vendor/sel4-src` 中 `.c` / `.S` 一一对应（阶段三源码镜像清单）。",
        'const std = @import("std");',
        "",
        "pub const entry_count: usize = count;",
        "",
        "pub fn pathAt(i: usize) []const u8 {",
        "    return entries[i];",
        "}",
        "",
        "const entries: [count][]const u8 = .{",
    ]
    zig_body: list[str] = []
    for p in all_files:
        rel = p.relative_to(ROOT).as_posix()
        zig_body.append(f'    "{rel}",')
    text = "\n".join(lines[:7])
    text = text.replace("count", str(len(all_files)))
    text += "\n" + "\n".join(zig_body) + "\n};\n"

    # Fix: replace placeholder properly
    text = f"""//! AUTO-GENERATED by tools/gen_vendor_manifest.py — do not edit by hand.
//! 列出 `vendor/sel4-src` 下 `.c`/`.S`（默认可为空；对照用官方树在仓外，默认 `../seL4/src`）。

pub const entry_count: usize = {len(all_files)};

pub fn pathAt(i: usize) []const u8 {{
    if (i >= entries.len) return "";
    return entries[i];
}}

const entries: [{len(all_files)}][]const u8 = .{{
""" + "\n".join(zig_body) + "\n};\n"

    ZIG.write_text(text, encoding="utf-8")

    # Markdown catalog by directory
    by_dir: dict[str, list[str]] = {}
    for p in all_files:
        d = str(p.parent.relative_to(SRC))
        by_dir.setdefault(d, []).append(p.name)

    with DOC.open("w", encoding="utf-8") as md:
        md.write("# seL4 内核源码模块清单（阶段一 / 阶段三镜像）\n\n")
        md.write("本文件由 `tools/gen_vendor_manifest.py` 根据 `vendor/sel4-src` 生成。\n\n")
        md.write(f"- **本地镜像文件数**: {len(all_files)}（`.c` + `.S`，`vendor/sel4-src`）\n")
        md.write("- **默认**: `vendor/sel4-src` 可为空；需要镜像清单时设 `FULL_VENDOR_MIRROR=1` 运行 `scripts/sync-vendor-from-upstream.sh`。\n")
        md.write("- **官方源码**: 外置 seL4 仓库的 `src/`、`include/`、`libsel4/`（本工程不内嵌 C 树）。\n\n")
        md.write("## 按子目录分组\n\n")
        for d in sorted(by_dir.keys()):
            md.write(f"### `{d}`\n\n")
            for name in sorted(by_dir[d]):
                md.write(f"- `{name}`\n")
            md.write("\n")

    print(f"Wrote {ZIG} ({len(all_files)} entries)")
    print(f"Wrote {DOC}")


if __name__ == "__main__":
    main()
